/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}"
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#4c3a6f",
        "on-secondary-container": "#773400",
        "surface-container": "#f5f4eb",
        "error-container": "#fb5151",
        "surface-tint": "#006e86",
        "secondary-fixed": "#ffc5a6",
        "tertiary-dim": "#614f86",
        "tertiary-fixed": "#cab4f3",
        "surface-container-high": "#efeee5",
        "on-primary-fixed": "#002c38",
        "inverse-on-surface": "#9e9d96",
        "outline-variant": "#bab9b2",
        "inverse-surface": "#0e0f0a",
        "on-tertiary-container": "#423166",
        "inverse-primary": "#00d2ff",
        "surface-container-lowest": "#ffffff",
        "error-dim": "#9f0519",
        "primary-dim": "#006177",
        "surface-bright": "#fefcf4",
        "on-tertiary-fixed": "#2d1b4f",
        "error": "#c0262d",
        "on-background": "#383833",
        "tertiary-container": "#cab4f3",
        "primary-fixed": "#00d2ff",
        "primary": "#006e86",
        "surface-container-low": "#fbf9f1",
        "background": "#fefcf4",
        "on-secondary-fixed-variant": "#853b00",
        "on-surface-variant": "#65655f",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ffb287",
        "on-primary": "#ffffff",
        "on-error-container": "#570008",
        "surface-dim": "#e4e3d8",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#592500",
        "surface-variant": "#e9e9de",
        "outline": "#81817a",
        "primary-fixed-dim": "#00c3ed",
        "secondary": "#a44a00",
        "secondary-dim": "#914100",
        "surface-container-highest": "#e9e9de",
        "secondary-container": "#ffc5a6",
        "on-surface": "#383833",
        "on-secondary": "#ffffff",
        "tertiary": "#6d5b93",
        "on-primary-container": "#004253",
        "surface": "#fefcf4",
        "primary-container": "#00d2ff",
        "tertiary-fixed-dim": "#bca6e4",
        "on-primary-fixed-variant": "#004c5e"
      },
      fontFamily: {
        "headline": ["Spline Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
